import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './providers';

const geistLexend = localFont({
  src: '../public/assets/fonts/Lexend/LexendDeca-VariableFont_wght.ttf',
  variable: '--font-geist-lexend',
  weight: '400 500 600',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistLexend.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
